name: image_search_cnn2
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch::pytorch
  - pytorch::faiss-cpu
  - orjson
  - opencv
  - numpy
  - transformers
  - pillow
  - scikit-image
  - scikit-learn
